name: maven build workflow

on:
  workflow_dispatch:
  push:
    branches: '*'

jobs:
  maven_build:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    steps:
      - name: checkout repo branches
        uses: actions/checkout@v7

#     - name: java install
#      run: |
#       sudo apt-get install openjdk-17-jdk -y
#      sudo apt install maven -y

      - name:
        uses: actions/setup-java@v5
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
      - name: build maven package
        run: mvn clean package
            
      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: spring-jar
          path: target/*.jar
          retention-days: 1

    build_image:
      needs: maven_build
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo branches
          uses: actions/checkout@v7

        - name: download artifacts
          uses: actions/download-artifact@v7
          with:
            name: spring-jar
            path: .

        - name: list files
          run:
            ls -lrt